# Welcome {.unnumbered}

How many times have you finished an analysis in R, took a step back and said, "Wow, that's so reproducible!" Yea, me neither. Despite its immense importance, reproducibility does not generate much fanfare and is often overlooked. Furthermore, what constitutes a reproducible workflow is not always clear. For example, If my R analysis yields the number 4, and I run the same analysis tomorrow with the same outcome (4), is my analysis considered **reproducible**?

The answer...*maybe?*

Despite the uncertainty, most reproducible analyses share certain attributes, including:

-   **Stable** - knowing an analysis will generate the *same outcome* today, tomorrow, a year from now, 10 years from now, etc.

-   **Shareable** - I can *share* my analysis with a colleague, a friend, a random person on the other side of the world, or my future self.

-   **Intuitive** - anyone can step into my analysis and know *how* to reproduce my work.

::: {.callout-note icon="false"}
# Goal of this book

To provide you with the skills and knowledge to create **reproducible** R analyses that are stable, shareable, and intuitive.
:::

## Book Structure

It's also the goal of this book to provide you with the **minimal skill-set** required to create reproducible analyses in R and will purposefully not be a deep dive into any one topic. Each chapter/topic in this book will provide you with a *foundational understanding* so that you can easily build you knowledge base and confidently explore any one topic in more detail. I will also include references when applicable for each topic to help guide deeper explorations.

Each chapter/topic will include the following:

-   A (often silly) story to help conceptualize the importance of each topic.

-   An overview of the topic geared towards R users that are new to reproducible analyses.

-   Minimal code and/or working example to get you started.

## License

This book is licensed under the [Creative Commons Attribution-NonCommercial-NoDerivs 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) License.

The code samples in this book are licensed under [Creative Commons CC0 1.0 Universal (CC0 1.0)](https://creativecommons.org/publicdomain/zero/1.0/), i.e. public domain.
